version: "3"
services:
  web:
    container_name: quest
    image: polysphere/crystal:1
    ports:
      - "3020:3000"
    volumes:
      - "./:/app"
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
