version: "3"
services:
  web:
    container_name: quest
    image: polysphere/crystal_quest:2
    restart: unless-stopped
    command: ["/app/crystal_quest"]
    networks:
      - web
networks:
  web:
    external: true
